apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
        - image: kayjoe/udagram-api-user:v8
          name: backend-user
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: NODE_OPTIONS
              value: --max-old-space-size=8192
            - name: URL
              value: http://aa14169d0c7404b33847e4ec1f57b17c-421867176.us-east-2.elb.amazonaws.com
            - name: AWS_MEDIA_BUCKET
              value: udagram-kelvin-dev
            - name: AWS_PROFILE
              value: default
            - name: AWS_REGION
              value: us-east-2
            - name: JWT_SECRET
              value: testing
            - name: POSTGRES_DATABASE
              value: postgres
            - name: POSTGRES_HOST
              value: postgres.co7krqtht9hp.us-east-2.rds.amazonaws.com
            - name: POSTGRES_PASSWORD
              value: college1
            - name: POSTGRES_USERNAME
              value: udagramkeldev
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_SECRET_ACCESS_KEY
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret